
path:
  train_data: /workspace/template_pipeline/data/titanic/train.csv
  test_data: /workspace/template_pipeline/data/titanic/test.csv
  eda_report: /workspace/template_pipeline/report/eda.html

dir:
  log: /workspace/template_pipeline/log/